# Generated by Django 4.2.30 on 2026-06-23 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(blank=True, default='', max_length=255)),
                ('candidate_email', models.EmailField(blank=True, default='', max_length=254)),
                ('candidate_phone', models.CharField(blank=True, default='', max_length=50)),
                ('client_name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('technology', models.CharField(max_length=255)),
                ('experience', models.DecimalField(decimal_places=1, max_digits=4)),
                ('recruiter', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('New', 'New'), ('Submitted', 'Submitted'), ('Under Review', 'Under Review'), ('Interview Scheduled', 'Interview Scheduled'), ('Interview Completed', 'Interview Completed'), ('Selected', 'Selected'), ('Rejected', 'Rejected'), ('On Hold', 'On Hold'), ('Closed', 'Closed')], default='New', max_length=50)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='applications.application')),
            ],
        ),
    ]
