# Generated by Django 4.2.30 on 2026-06-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
