# Generated by Django 4.2.30 on 2026-07-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_application_city_application_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Submitted', 'Placed'), ('Under Review', 'Under Review'), ('Interview Scheduled', 'Interview Scheduled'), ('Interview Completed', 'Interview Completed'), ('Offer Sent', 'Offer Sent'), ('Offer Accepted', 'Offer Accepted'), ('Selected', 'Selected'), ('Rejected', 'Rejected'), ('On Hold', 'On Hold'), ('Closed', 'Closed')], default='New', max_length=50),
        ),
    ]
