# Generated by Django 4.2.30 on 2026-07-17 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='aadhaar',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='application',
            name='alternate_mobile_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='application',
            name='interest_to_work_for_client',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='application',
            name='pan_card',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='application',
            name='source',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
