# Generated by Django 4.2.30 on 2026-07-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_application_aadhaar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='modified_by',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
