# Generated by Django 4.2.30 on 2026-07-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_application_modified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Submitted', 'Submitted'), ('Placed', 'Placed'), ('Under Review', 'Under Review'), ('Interview Scheduled', 'Interview Scheduled'), ('Interview Completed', 'Interview Completed'), ('Offer Sent', 'Offer Sent'), ('Offer Accepted', 'Offer Accepted'), ('Offer Rejected', 'Offer Rejected'), ('Selected', 'Selected'), ('Rejected', 'Rejected'), ('On Hold', 'On Hold'), ('Closed', 'Closed')], db_index=True, default='New', max_length=50),
        ),
    ]
