# Generated by Django 4.2.30 on 2026-07-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='publish_to_career_page',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='publish_to_linkedin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
