# Generated by Django 4.2.30 on 2026-07-31 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_add_career_portal_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerPortalApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('mobile_number', models.CharField(max_length=50)),
                ('alternate_mobile_number', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('qualification', models.CharField(max_length=255)),
                ('years_of_experience', models.DecimalField(decimal_places=1, max_digits=4)),
                ('expected_pay', models.DecimalField(decimal_places=2, max_digits=12)),
                ('primary_skills', models.TextField()),
                ('current_ctc', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_company', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('resume', models.TextField(blank=True, default='')),
                ('accepted_terms', models.BooleanField(default=True)),
                ('source', models.CharField(default='Company Career Portal', max_length=100)),
                ('status', models.CharField(default='New', max_length=50)),
                ('is_imported', models.BooleanField(db_index=True, default=False)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('imported_by', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imported_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originating_portal_applicant', to='applications.application')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_portal_applicants', to='applications.application')),
            ],
        ),
    ]
