# Generated by Django 4.2.30 on 2026-07-31 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_careerportalapplicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerportalapplicant',
            name='modified_by',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
