# Generated by Django 4.2.30 on 2026-08-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_careerportalapplicant_modified_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerportalapplicant',
            name='ai_match_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerportalapplicant',
            name='ai_scored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
