# Generated by Django 4.2.30 on 2026-08-11 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0013_careerportalapplicant_ai_match_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='country',
            field=models.CharField(blank=True, default='India', max_length=100),
        ),
    ]
