# Generated by Django 4.2.30 on 2026-08-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0014_application_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ai_job_embedding',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='careerportalapplicant',
            name='ai_match_score',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
    ]
