# Generated by Django 4.2.30 on 2026-08-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0015_application_ai_job_embedding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ai_job_embedding_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='ai_job_embedding_nemotron',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerportalapplicant',
            name='ai_match_score_nemotron',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
    ]
