# Generated by Django 4.2.30 on 2026-08-24 06:52

from django.db import migrations, models
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0016_application_ai_job_embedding_metadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='embedding_dimension',
            field=models.IntegerField(default=2048),
        ),
        migrations.AddField(
            model_name='application',
            name='embedding_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='embedding_model',
            field=models.CharField(default='nvidia/nemotron-3-embed-1b', max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='embedding_version',
            field=models.CharField(default='nemotron-v1', max_length=50),
        ),
        migrations.AddField(
            model_name='application',
            name='job_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=2048, null=True),
        ),
        migrations.AddField(
            model_name='careerportalapplicant',
            name='embedding_dimension',
            field=models.IntegerField(default=2048),
        ),
        migrations.AddField(
            model_name='careerportalapplicant',
            name='embedding_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerportalapplicant',
            name='embedding_model',
            field=models.CharField(default='nvidia/nemotron-3-embed-1b', max_length=100),
        ),
        migrations.AddField(
            model_name='careerportalapplicant',
            name='embedding_version',
            field=models.CharField(default='nemotron-v1', max_length=50),
        ),
        migrations.AddField(
            model_name='careerportalapplicant',
            name='resume_content_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='careerportalapplicant',
            name='resume_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=2048, null=True),
        ),
        migrations.AddField(
            model_name='careerportalapplicant',
            name='score_education',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerportalapplicant',
            name='score_experience',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerportalapplicant',
            name='score_semantic',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerportalapplicant',
            name='score_skills',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerportalapplicant',
            name='score_title',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
