# Generated by Django 4.2.30 on 2026-10-06 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0017_application_embedding_dimension_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerportalapplicant',
            name='foundit_application_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='careerportalapplicant',
            name='foundit_candidate_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='JobBoardPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_board', models.CharField(choices=[('Foundit', 'Foundit')], db_index=True, max_length=50)),
                ('external_job_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('UNPUBLISHED', 'Unpublished'), ('PENDING', 'Pending'), ('PUBLISHED', 'Published'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired / Closed')], db_index=True, default='UNPUBLISHED', max_length=50)),
                ('external_url', models.URLField(blank=True, default='', max_length=500)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_board_postings', to='applications.application')),
            ],
            options={
                'verbose_name': 'Job Board Posting',
                'verbose_name_plural': 'Job Board Postings',
                'unique_together': {('job', 'job_board')},
            },
        ),
    ]
