# Generated by Django 4.2.30 on 2026-06-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin (Superuser)'), ('CEO', 'CEO'), ('SENIOR_MANAGER', 'Senior Manager'), ('JUNIOR_MANAGER', 'Junior Manager'), ('TEAM_LEAD', 'Team Lead'), ('SUB_LEAD', 'Sub Lead'), ('SENIOR_ANALYST', 'Senior Analyst'), ('ASSOCIATE_ANALYST', 'Associate Analyst')], default='ASSOCIATE_ANALYST', max_length=50),
        ),
    ]
