# Generated by Django 4.2.30 on 2026-07-03 05:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_initial'),
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='team',
        ),
        migrations.AddField(
            model_name='user',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='members', to='teams.team'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='reporting_to',
        ),
        migrations.AddField(
            model_name='user',
            name='reporting_to',
            field=models.ManyToManyField(blank=True, related_name='reporters', to=settings.AUTH_USER_MODEL),
        ),
    ]
