# Generated by Django 4.2.30 on 2026-07-07 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_team_user_teams_remove_user_reporting_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin (Superuser)'), ('CEO', 'CEO'), ('SENIOR_MANAGER', 'Senior Manager'), ('JUNIOR_MANAGER', 'Junior Manager'), ('TEAM_LEAD', 'Team Lead'), ('SUB_LEAD', 'Sub Lead'), ('SENIOR_ANALYST', 'Senior Analyst'), ('ASSOCIATE_ANALYST', 'Associate Analyst'), ('REPORTING_TEAM', 'Reporting Team')], default='ASSOCIATE_ANALYST', max_length=50),
        ),
    ]
